### ISSUE TITLE
not showing setting

### ISSUE THREAD

**Issue by ivoryxiong** [dtrukr/FLEX_injected#1]
OS :  8.1 (12B411)
Device : iPod touch 5

install release version

**Comment by upbit** [comment]
Try this, I recompile with latest FLEX source: [com.daapps.FLEXInjected_0.0.1-FLEX_e3612e3.deb](http://blog.imaou.com/assets/download/com.daapps.FLEXInjected_0.0.1-FLEX_e3612e3.deb)

It works great for my iPhone4S(iOS8.1):
![FLEX_injected](http://blog.imaou.com/images/201502/FLEX_injected_wechat.png)

**Comment by dtrukr** [comment]
Should be fixed in the latest release that uses FLEX 2.0.2:
https://github.com/dtrukr/FLEX_injected/releases/tag/2.0.2
